### ISSUE TITLE
Searching for 'libtiff' in repology search doesn't return the 'tiff' result

### ISSUE THREAD

**Issue by luzpaz** [repology/repology-rules#219] opened 2019-07-12 20:50 UTC
Even though the following repology rule exists: 
https://github.com/repology/repology-rules/blob/master/800.renames-and-merges/t.yaml#L80 

~~https://repology.org/projects/..suse32-libtiff/?search=libtiff~~
https://repology.org/projects/?search=libtiff&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=      
https://repology.org/project/tiff/versions

**Comment by luzpaz** [comment] 2019-07-12 20:58
Similar issue with searching for `libjpg` or `jpg` though to be fair there are no rules that setname libjpg to libjpeg.

**Comment by AMDmi3** [comment] 2019-07-12 22:13
Duplicate of repology/repology#763 and wrong repository.

**Closed by AMDmi3** 2019-07-12 22:13 UTC
