### ISSUE TITLE
Nixpkgs missing its Emacs packages

### ISSUE THREAD

**Issue by Atemu** [repology/repology-rules#396] opened 2020-07-30 13:33 UTC
Nixpkgs has packaged 254 ELPA and 4601 MELPA packages but none of them show up on repology.org.

They're available under the `emacs{25,26}Packages` attribute sets (https://search.nixos.org/packages?query=emacs26Packages&from=0&size=10000&sort=relevance&channel=unstable).

**Comment by AMDmi3** [comment] 2020-07-30 14:08
```
% wget -qO- https://channels.nixos.org/nixos-unstable/packages.json.br | brotli -d | grep emacs26Packages
%
```

**Comment by Atemu** [comment] 2020-07-30 18:12
That's odd.

These definitely are available in Nixpkgs if you evaluate it and the new search page shows them aswell (see link in OP).

I've investigated a bit further and found that nodePackages, perlPackages, luaPackages and texlive packages are also missing. 
Some of those do not show up in the new search page either.

I've also looked into how that JSON is generated. It's the result of `nix-env -qa` which I don't think is a very good source for repository information.  
@samueldr @garbas, do we have better sources other than Nixpkgs itself?

Although, would making Repology evaluate Nixpkgs directly be feasible @AMDmi3? That'd be the most accurate source.

**Comment by samueldr** [comment] 2020-07-30 18:36
The issue is that adding a "sub package set" is costly for the packages search interface. Adding new packages into it made the issues with (the older, and the old) package search problematic.

We can look into producing a full list that is independently used for repology import (and other people's data scraping desires).

**Comment by AMDmi3** [comment] 2020-07-31 13:58
> would making Repology Repology evaluate Nixpkgs directly be feasible

Definitely no. I won't do any complex parsing and depend on third party software.

> We can look into producing a full list that is independently used for repology import (and other people's data scraping desires).

That would be a solution.

**Comment by AMDmi3** [comment] 2020-08-27 17:56
Closing since there's nothing to do here on repology side.

**Closed by AMDmi3** 2020-08-27 17:56 UTC

**Comment by Atemu** [comment] 2020-12-24 15:32
Problem has been resolved!
