### ISSUE TITLE
Debian package missing from python:readability-lxml

### ISSUE THREAD

**Issue by City-busz** [repology/repology-rules#834] opened 2024-08-01 10:50 UTC
The Debian binary package [python3-readability](https://packages.debian.org/sid/python3-readability) is not listed on [python:readability-lxml](https://repology.org/project/python:readability-lxml/versions), but it's on a separated [readability](https://repology.org/project/readability/versions) page. Please merge them!

**Comment by AMDmi3** [comment] 2024-08-01 11:22
Duplicate of #833. Source python packages in Debian must have a distinguishable naming scheme (similar to what's used to other ecosystems, e.g. `lib*-ruby`, `lib*-perl`, `libphp-*`, `rust-*` etc.) to be merged to corresponding Repology `python:` projects. This specific package is also incorrectly named, as it's in fact [readability-xml](https://pypi.org/project/readability-lxml/), and not unrelated [readability](https://pypi.org/project/readability/).

**Closed** 2024-08-01 11:22 UTC

**Comment by City-busz** [comment] 2024-08-01 11:39
This is so bad! I thought that Repology is supposed to match the same packages in different distributions, but it seems that isn't true.

**Comment by AMDmi3** [comment] 2024-08-01 11:51
It's supposed to, but if the distribution provides incomplete or invalid data it's simply not possible.
